<?xml version="1.0"?>
<package format="3">
  <name>aegisinspect_bringup</name>
  <version>0.1.0</version>
  <description>Minimal Stop-B simulation and static-frame bringup.</description>
  <maintainer email="AritraAcherjee@users.noreply.github.com">Aritra Acherjee</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>aegisinspect_description</exec_depend>
  <exec_depend>aegisinspect_sim</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
